# Generated by Django 2.2.2 on 2020-11-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='img_name',
            field=models.CharField(max_length=255),
        ),
    ]
