# Generated by Django 2.2.2 on 2020-11-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_upload', '0002_auto_20201122_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(upload_to='image_database'),
        ),
    ]
