# Generated by Django 2.2.2 on 2020-11-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_upload', '0005_auto_20201122_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='img_name',
            field=models.TextField(),
        ),
    ]
