# Generated by Django 2.2.2 on 2020-11-23 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('img_upload', '0007_auto_20201122_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.CreateModel(
            name='add_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('img_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='img_upload.Upload')),
            ],
        ),
    ]
