# Generated by Django 2.2.2 on 2020-11-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_upload', '0014_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('img_name', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
