# Generated by Django 2.2.2 on 2020-11-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_upload', '0015_auto_20201123_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='ocr',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
